[project]
name = "manimations"
version = "0.1.0"
description = "Video project on Bayes Theorem for school"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "audioop-lts>=0.2.2",
    "manim==0.18.1",
    "pydantic>=2.12.4",
]
